GCC_730_BIN=/usr/bin
LLVM_50_INSTALL=/home/vi3/gcc/llvm-project/openmp/openmp-install

cmake .. -DCMAKE_INSTALL_PREFIX:PATH=${LLVM_50_INSTALL} -DCMAKE_C_COMPILER=${GCC_730_BIN}/gcc -DCMAKE_CXX_COMPILER=${GCC_730_BIN}/g++ -DCMAKE_Fortran_COMPILER=${GCC_730_BIN}/gfortran  -DLIBOMP_OMPT_SUPPORT=TRUE -DLIBOMP_FORTRAN_MODULES=ON
